trigger:
    - master

jobs:
 - job: Sawyer
   timeoutInMinutes: 120
   pool:
     name: 'nvidia-docker-pool'

   steps:
   - task: Bash@3
     inputs:
       workingDirectory: 'docker/ubuntu-xenial-kinetic'
       targetType: 'inline'
       script: './build.sh'
   - task: Bash@3
     timeoutInMinutes: 10
     inputs:
       workingDirectory: 'docker/ubuntu-xenial-kinetic'
       targetType: 'inline'
       script: './run_docker_container.sh'
     env:
       DISPLAY: :0.0
   - task: Bash@3
     inputs:
       script: docker rmi ubuntu1604_sawyer
